// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzWZDKlBeMTLIQQZjxhGlhHsGtfzewFs',
    appId: '1:196979651016:web:dcbc00c362e66ef21850fd',
    messagingSenderId: '196979651016',
    projectId: 'chat-app-ac105',
    authDomain: 'chat-app-ac105.firebaseapp.com',
    storageBucket: 'chat-app-ac105.appspot.com',
    measurementId: 'G-71628N2KQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9e7ePTZjl3uvq4DR536BSKeCoPX9b2s',
    appId: '1:196979651016:android:668191aefcee34ce1850fd',
    messagingSenderId: '196979651016',
    projectId: 'chat-app-ac105',
    storageBucket: 'chat-app-ac105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBipnrwHnmLoAc_B1-hq_BmEz6ELNBZC0Q',
    appId: '1:196979651016:ios:11cdf2eefe70ef411850fd',
    messagingSenderId: '196979651016',
    projectId: 'chat-app-ac105',
    storageBucket: 'chat-app-ac105.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBipnrwHnmLoAc_B1-hq_BmEz6ELNBZC0Q',
    appId: '1:196979651016:ios:82c5f91275bec8801850fd',
    messagingSenderId: '196979651016',
    projectId: 'chat-app-ac105',
    storageBucket: 'chat-app-ac105.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
